import Header from "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const garet = localFont({
  src: [
    {
      path: "../../public/fonts/Garet-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Book.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Book.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Book.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Heavy.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Heavy.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Heavy.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Garet-Heavy.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-garet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garet.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}