// Client-side configuration - only public environment variables
const clientConfig = {
  AGORA_PUBLIC_ID: process.env.NEXT_PUBLIC_AGORA_APP_ID,
  FIREBASE_API_KEY_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  APP_ID_PUBLIC: process.env.NEXT_PUBLIC_APP_ID,
  STRIPE_KEY_PUBLIC: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  API_BASE_URL_PUBLIC: process.env.NEXT_PUBLIC_API_BASE_URL,
  EMAIL_SERVER_URL_PUBLIC: process.env.NEXT_PUBLIC_EMAIL_SERVER_URL,
  DOBA_API_URL_PUBLIC: process.env.NEXT_PUBLIC_DOBA_API_URL,
  GIFT_SYSTEM_ENABLED_PUBLIC: process.env.NEXT_PUBLIC_GIFT_SYSTEM_ENABLED,
  GIFT_SYSTEM_DEBUG_PUBLIC: process.env.NEXT_PUBLIC_GIFT_SYSTEM_DEBUG,
  STRIPE_KEY_PUBLIC_ALT: process.env.NEXT_PUBLIC_STRIPE_KEY,
  GOOGLE_PLACES_KEY_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,
  GOOGLE_PLACE_ID_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_PLACE_ID,
  GOOGLE_REVIEWS_ENABLED_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_ENABLED,
  GOOGLE_REVIEWS_CACHE_DURATION_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_CACHE_DURATION,
  VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
  
  // Google Analytics Configuration
  GOOGLE_ANALYTICS_ID: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID,
  GOOGLE_TAG_MANAGER_ID: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
} as const;

export default clientConfig;
