// Server-side configuration - environment variables are loaded by Next.js

const config = {
  AGORA_PUBLIC_ID: process.env.NEXT_PUBLIC_AGORA_APP_ID,
  AGORA_ID: process.env.AGORA_APP_ID,
  AGORA_CERT: process.env.AGORA_APP_CERTIFICATE,
  MONGO_URI: process.env.MONGODB_URI,

  FIREBASE_API_KEY_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET_PUBLIC:
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID_PUBLIC:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID_PUBLIC: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID_PUBLIC:
    process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,

  APP_ID_PUBLIC: process.env.NEXT_PUBLIC_APP_ID,
  ZEGO_SECRET: process.env.ZEGO_SERVER_SECRET,

  STRIPE_KEY_PUBLIC: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,

  API_BASE_URL_PUBLIC: process.env.NEXT_PUBLIC_API_BASE_URL,
  EMAIL_SERVER_URL_PUBLIC: process.env.NEXT_PUBLIC_EMAIL_SERVER_URL,

  DOBA_API_URL_PUBLIC: process.env.NEXT_PUBLIC_DOBA_API_URL,
  DOBA_KEY: process.env.DOBA_API_KEY,
  DOBA_RETAILER: process.env.DOBA_RETAILER_ID,

  GIFT_SYSTEM_ENABLED_PUBLIC: process.env.NEXT_PUBLIC_GIFT_SYSTEM_ENABLED,
  GIFT_SYSTEM_DEBUG_PUBLIC: process.env.NEXT_PUBLIC_GIFT_SYSTEM_DEBUG,

  NODE_ENVIRONMENT: process.env.NODE_ENV,

  STRIPE_KEY_PUBLIC_ALT: process.env.NEXT_PUBLIC_STRIPE_KEY,

  GOOGLE_PLACES_KEY_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,
  GOOGLE_PLACE_ID_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_PLACE_ID,
  GOOGLE_REVIEWS_ENABLED_PUBLIC: process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_ENABLED,
  GOOGLE_REVIEWS_CACHE_DURATION_PUBLIC:
    process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_CACHE_DURATION,

  VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,

  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,

  // Authentication
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  // Email Configuration
  EMAIL_HOST: process.env.EMAIL_HOST,
  EMAIL_PORT: process.env.EMAIL_PORT,
  EMAIL_SECURE: process.env.EMAIL_SECURE,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASS: process.env.EMAIL_PASS,




} as const;

export default config;
